<a href="https://colab.research.google.com/github/rivera-squared/Educacion_Machine_Learning/blob/main/Logistic%20Model%20alternate.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Logistic Regression Model

In [16]:
import pandas as pd
import numpy as np

In [25]:
# Import the necessary modules
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_auc_score
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import StandardScaler

In [18]:
# New data set with 'cambio_matricula' column
x = pd.read_csv('https://raw.githubusercontent.com/edghero/data/main/escuelas_nuevas.csv').dropna()

In [19]:
x['cambio_matricula'] = pd.to_numeric(x['cambio_matricula'], errors = 'coerce')

In [20]:
# renaming nivel to match DE's current naming convention. I NEED TO GO OVER INTERLOCKING ONE BY ONE TO RECLASS THEM PROPERLY
x['nivel'] = np.where(x['nivel'] == 'elemental', 'primario',
                      np.where(x['nivel'] == 'intermedia','primario',
                               np.where(x['nivel'] == 'especializada','todos los niveles',
                                        np.where(x['nivel'] == 'superior', 'secundario',
                                                 np.where(x['nivel'] == 'interlocking','todos los niveles','otro')))))

In [21]:
x = x[['region','nivel','consolidada','matricula','cambio_matricula','promedio_espanol','promedio_matematica','promedio_ingles','promedio_ciencias']]

# Logistic Model Escuelas primarias: y(consolidada 1=yes, 0=no) = β1(matricula) + β2(cambio_matricula)

### Scaled features

In [31]:
# Filtering by escuelas nivel primario
primario = x[x['nivel'] == 'primario'].drop(columns = ['nivel','region'])
X = primario.drop(columns = 'consolidada')
y = primario['consolidada']

scaler= StandardScaler()
X_subset= X[['matricula', 'cambio_matricula']]
X_scaled = pd.DataFrame(scaler.fit_transform(X_subset),
                        columns = X_subset.columns)

In [32]:
# Create training and test sets
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size = 0.30, random_state=42)

# Create the classifier: logreg
logreg = LogisticRegression()

# Fit the classifier to the training data
logreg.fit(X_train, y_train)

# Predict the labels of the test set: y_pred
y_pred = logreg.predict(X_test)

# Compute and print the confusion matrix and classification report
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[115  24]
 [ 18  39]]
              precision    recall  f1-score   support

           0       0.86      0.83      0.85       139
           1       0.62      0.68      0.65        57

    accuracy                           0.79       196
   macro avg       0.74      0.76      0.75       196
weighted avg       0.79      0.79      0.79       196



### Unscaled features

In [34]:
# Create training and test sets
X_train, X_test, y_train, y_test = train_test_split(X[['matricula','cambio_matricula']], y, test_size = 0.30, random_state=42)

# Create the classifier: logreg
logreg = LogisticRegression()

# Fit the classifier to the training data
logreg.fit(X_train, y_train)

# Predict the labels of the test set: y_pred
y_pred = logreg.predict(X_test)

# Compute and print the confusion matrix and classification report
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[115  24]
 [ 18  39]]
              precision    recall  f1-score   support

           0       0.86      0.83      0.85       139
           1       0.62      0.68      0.65        57

    accuracy                           0.79       196
   macro avg       0.74      0.76      0.75       196
weighted avg       0.79      0.79      0.79       196



# Logistic Model Escuelas primarias: y(consolidada 1=yes, 0=no) = β1(matricula) + β2(cambio_matricula) + β3 (promedio_espanol) + β4 (promedio_matematica) + β5 (promedio_ingles) + β6 (promedio_ciencias)

In [38]:
# Create training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.30, random_state=42)

# Create the classifier: logreg
logreg = LogisticRegression()

# Fit the classifier to the training data
logreg.fit(X_train, y_train)

# Predict the labels of the test set: y_pred
y_pred = logreg.predict(X_test)
# Compute and print the confusion matrix and classification report
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[116  23]
 [ 20  37]]
              precision    recall  f1-score   support

           0       0.85      0.83      0.84       139
           1       0.62      0.65      0.63        57

    accuracy                           0.78       196
   macro avg       0.73      0.74      0.74       196
weighted avg       0.78      0.78      0.78       196

